name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, linux ]

    env:
      ANDROID_HOME: $HOME/android-sdk

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          
          wget -O commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools.zip
          
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
          wget -O platform-tools.tar.xz https://github.com/AndroidIDEOfficial/platform-tools/releases/download/v34.0.4/platform-tools-34.0.4-aarch64.tar.xz
          tar -xf platform-tools.tar.xz
          rm platform-tools.tar.xz
          
          echo "$ANDROID_HOME/build-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses

      - name: Setup Release Keystore
        run: |
          rm -f keystore.properties
          touch keystore.properties
          
          echo "RELEASE_STORE_FILE:./keystore/release.keystore" >> keystore.properties
          echo "RELEASE_STORE_PASSWORD:${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
          echo "RELEASE_KEY_ALIAS:${{ secrets.RELEASE_KEY_ALIAS }}" >> keystore.properties
          echo "RELEASE_KEY_PASSWORD:${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties
          
          mkdir -p ./app/keystore
          echo "${{ secrets.RELEASE_STORE_FILE }}" | base64 --decode > ./app/keystore/release.keystore

      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Rename APK
        run: |
          APK_PATH=./app/build/outputs/apk/release/app-release.apk
          
          PACKAGE_NAME=$(aapt dump badging "$APK_PATH" | grep "package: name=" | sed -n "s/.*package: name='\([^']*\).*/\1/p")
          VERSION_NAME=$(aapt dump badging "$APK_PATH" | grep "versionName=" | sed -n "s/.*versionName='\([^']*\).*/\1/p")
          
          echo "OUTPUT_NAME=$PACKAGE_NAME-$VERSION_NAME-$GITHUB_RUN_NUMBER.apk" >> $GITHUB_ENV
          echo ${{ env.OUTPUT_NAME }}
          
          mv "./app/build/outputs/apk/release/app-release.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}
